<a href="https://colab.research.google.com/github/trirex79/python/blob/main/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Strona biblioteki: https://numpy.org/
Dokumentacja: https://numpy.org/doc/

Podstawowa biblioteka do obliczeń numerycznych w języku Python.

Aby zainstalować bibliotekę NumPy, użyj polecenia: pip install numpy

#Podstawy

In [1]:
pip install numpy;

In [4]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

>[Podstawy](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=akEEvekxQZ0D)

>[ARRAY](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=oKo8M0tnR41T)

>>[Array 1D](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=--ny58GGRfxC)

>>[Array 2D](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=r_K16XwUVbqi)

>>[Array 3D](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=yrdK7DsjXkKD)

>[Typy danych](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=y82nxc50aD4w)

>[Tworzenie tabli aytomatycznie](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=5LNr0bOpdPWm)

>[Podstawowe operacje na tablicach](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=lXaBPrK6jEHA)

>>>[Mnożenie macierzy](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=aBl0FBLVlOSq)

>>>[Jak mnożymy macierze:](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=7GuQTYtHpz9P)

>>>>[(1 w 1 k)                       ; (1 wiersz 2 kolumna)](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=7GuQTYtHpz9P)

>>>>[(2 w 1k )                      ; (2 wiersz 2 kolumna)](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=7GuQTYtHpz9P)

>[Generowani liczby pseudolosowych](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=OR4XIuR8rIeV)

>[Podstawowe funkcje biblioteki numpy](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=PqMB78g1Cfr3)

>[Indeksowanie i wycinanie](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=OPF5wb74J9XE)

>[Iteracja po tablicach](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=jK_jEkv6M9D2)

>[Zmiana rozmiaru tablicy](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=gTSSnXwRN_-z)

>[Maski logiczne](#updateTitle=true&folderId=1Fsd6YlTlAP1oIWxYZ0V8HY38Asw6IpDb&scrollTo=WfkqhXA_PBUm)



#ARRAY
Wszystkie obiekty muszą być tego samego typu

##Array 1D

In [21]:
arr1 = np.array([1.5,3.2,4.1])
arr1
print(arr1)


[1.5 3.2 4.1]


In [22]:
type(arr1)

numpy.ndarray

In [23]:
arr1.ndim

1

In [24]:
arr1.shape

(3,)

In [25]:
arr1.size

3

In [26]:
arr1.dtype

dtype('float64')

##Array 2D

In [29]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [35]:
y = np.array([['aaa','bbb','ccc'],['ddd','eee','bbb']])
y

array([['aaa', 'bbb', 'ccc'],
       ['ddd', 'eee', 'bbb']], dtype='<U3')

In [30]:
x.ndim

2

In [36]:
y.ndim

2

In [31]:
x.shape

(2, 2)

In [37]:
y.shape

(2, 3)

In [32]:
x.size

4

In [33]:
x.dtype

dtype('int64')

In [38]:
y.dtype

dtype('<U3')

##Array 3D

In [48]:
z = np.array([
              [[1,4,5],[5,7,9]],
              [[1,2,3],[4,5,6]],
              [[1,4,5],[5,7,9]],
              [[1,2,3],[4,5,6]]
            ])
z

array([[[1, 4, 5],
        [5, 7, 9]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 4, 5],
        [5, 7, 9]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [49]:
z.ndim #3 wymiary

3

In [42]:
z.size

12

In [50]:
z.shape
# 4 tablice, 2 wiersze, 3 kolumny

(4, 2, 3)

#Typy danych

In [51]:
A =np.array([1,7,2])
A.dtype

dtype('int64')

In [52]:
A = np.array([1.5 ,2.6])
A.dtype

dtype('float64')

In [53]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [56]:
A = np.array([1,2,3], dtype='complex') #typy złożone
A.dtype

dtype('complex128')

In [55]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [57]:
B = np.array([1.1 ,2.2 ,3.0 ], dtype='int') #niejawna konwersja
B.dtype

dtype('int64')

In [58]:
B

array([1, 2, 3])

In [61]:
C =np.array([True,False])  # z dużej litery
C.dtype

dtype('bool')

In [63]:
pixel = np.array([120,230,255], dtype=np.uint8) # unsign int od 0 do 225 wystarczy do RGB
pixel.dtype

dtype('uint8')

#Tworzenie tabli aytomatycznie

In [69]:
q = np.zeros(shape=(4,10))
q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
q.dtype #domyślny typ float

dtype('float64')

In [70]:
r = np.ones(shape=(5,8), dtype = np.uint8)
r

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [71]:
p = np.full(shape=(4,4),fill_value=5, dtype='int')
p

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [73]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [80]:
np.arange(start =100, stop=-20, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0, -10])

In [82]:
np.arange(start =0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [77]:
range(10)

range(0, 10)

In [78]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
np.linspace(start=0, stop=9 , num= 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
A.reshape((5,-1)) # 5 wierszy i odpowiednia liczba kolum  -1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [95]:
A.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#Podstawowe operacje na tablicach

In [96]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [97]:
A + B #aby dodać rozmiar musi się zgadzać 

array([6, 0, 7, 4])

In [98]:
A / B # druga tablica nie może zawierać zer

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [104]:
np.add(A,B)

array([6, 0, 7, 4])

In [105]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [106]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [107]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [108]:
np.absolute(B) #wartość bezwzględna

array([3, 1, 3, 2])

In [101]:
A + 7

array([10,  8, 11,  9])

In [102]:
(A +7) + B

array([13,  7, 14, 11])

In [103]:
A + 3*B

array([12, -2, 13,  8])

### Mnożenie macierzy

In [109]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [110]:
X * Y #mnożenie po elemencie

array([[6, 0],
       [2, 0]])

In [111]:
np.dot(X,Y) #mnożenie macierzowe - wiersz razy kolumna - licza wierszy Y musi być = liczba kolum X

array([[  3,   6],
       [-12,   0]])

###Jak mnożymy macierze:
####(1 w 1 k)                       ; (1 wiersz 2 kolumna)
(1 * 6 ) + ( 3 * -1) = 3.     ; (1 * 0) + (3 * 2) = 6
####(2 w 1k )                      ; (2 wiersz 2 kolumna) 
(-2 * 6 ) + (0 * -1) =  -12 ; (-2 *0 ) + (0 * 2 ) =0

In [112]:
X.dot(Y) #pomnóż macierz X przez macierz Y

array([[  3,   6],
       [-12,   0]])

In [113]:
Y.dot(X) # mnożenie macierzy nie jest przemienne 

array([[ 6, 18],
       [-5, -3]])

In [114]:
Y @ X #pomnóż macierz Y przez macierz X

array([[ 6, 18],
       [-5, -3]])

#Generowani liczby pseudolosowych

In [116]:
np.random.seed(0) #ustawiamy ziarno losowe, jeżeli ziarno się nie zmienia wynik losowania zawsze będzie taki sam!

In [117]:
np.random.randn()  # losowa wartość z rozkładu normalnego

1.764052345967664

In [119]:
np.random.randn(10)  # 10 losowych wartości z rozkładu normalnego standardowego czyli wartość 0 odchylenie 1 

array([ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433,
        1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982])

In [120]:
np.random.randn(10,4) #kolumny - zmienne, wiersze - próbki

array([[ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785],
       [-0.21274028, -0.89546656,  0.3869025 , -0.51080514],
       [-1.18063218, -0.02818223,  0.42833187,  0.06651722],
       [ 0.3024719 , -0.63432209, -0.36274117, -0.67246045]])

In [126]:
np.random.rand() #rozkład jednostajny na przedziale <0;1)

0.5013243819267023

In [124]:
np.random.rand(10)

array([0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949,
       0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895])

In [125]:
np.random.rand(10,3)

array([[0.66741038, 0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136, 0.58651293],
       [0.02010755, 0.82894003, 0.00469548],
       [0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733],
       [0.59204193, 0.57225191, 0.22308163],
       [0.95274901, 0.44712538, 0.84640867],
       [0.69947928, 0.29743695, 0.81379782],
       [0.39650574, 0.8811032 , 0.58127287],
       [0.88173536, 0.69253159, 0.72525428]])

In [127]:
np.random.randint(10) #może zwrócić 0,1,2,3,4,5,6,7,8,9

3

In [128]:
np.random.randint(low=10, high=101)

43

In [129]:
np.random.randint(low=10, high=101, size=10)

array([42, 80, 95, 41, 23, 81, 66, 34, 89, 51])

In [133]:
np.random.choice([2,-8,-3,6,0] ) #losowy element z listy

-8

In [135]:
np.random.choice(['python','R','C++','sql'] )

'sql'

In [136]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.random.shuffle(data)
data

array([9, 4, 2, 1, 8, 3, 5, 6, 7, 0])

#Podstawowe funkcje biblioteki numpy

In [142]:
np.exp(1) #liczba Eulera

2.718281828459045

In [143]:
np.sqrt(9)

3.0

In [144]:
np.all([1,4,7])

True

In [146]:
np.all([1,0,2]) #jeżeli którakolwiek wartość zwraca false wynikiem jest false

False

In [148]:
np.any([1,0,3,0]) #jeżeli którakolwiekwartość zwraca true - wynikiem jest true

True

In [149]:
np.any([0,0,0])

False

In [150]:
A = np.random.rand(5)
A

array([0.7142413 , 0.99884701, 0.1494483 , 0.86812606, 0.16249293])

In [151]:
np.argmax(A) #zwraca indeks największej wartości

1

In [152]:
A[1]

0.9988470065678665

In [153]:
A[np.argmax(A)]

0.9988470065678665

In [154]:
np.argmin(A)

2

In [155]:
np.argsort(A) #sortuje od nnajmniejszej i zwraca indexsy

array([2, 4, 0, 3, 1])

In [157]:
np.max(A)

0.9988470065678665

In [158]:
np.mean(A)

0.5786311205639121

In [159]:
np.median(A)

0.7142412995491114

In [160]:
np.std(A) #odchylenie standardowe

0.3566925031879748

#Indeksowanie i wycinanie

In [162]:
A =np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [163]:
A[3]

3

In [164]:
A[3:7]

array([3, 4, 5, 6])

In [165]:
A[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [166]:
A[9:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [168]:
A[[3,7,9]]

array([3, 7, 9])

In [169]:
A[[-1,-3,-5]] # indeksowanie od tyłu

array([19, 17, 15])

In [171]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [172]:
A[1] #wycinanie wiersza

array([5, 6, 7, 8, 9])

In [174]:
A[:,1] #wycinanie kolumny

array([ 1,  6, 11, 16])

In [175]:
A[:,-1] #ostatnia kolumna

array([ 4,  9, 14, 19])

In [176]:
A[0,3]

3

In [179]:
A[3,0] #4 wiersz 1 kolumna

15

In [180]:
A[1:3,1:4] # przedział zawsze lewostronnie domknięty, prawostronnie otwart

array([[ 6,  7,  8],
       [11, 12, 13]])

In [181]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#Iteracja po tablicach

In [182]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [183]:
for row in A:
  print(row[1])

1
6
11
16


In [184]:
for row in A:
  print(row[:2])

[0 1]
[5 6]
[10 11]
[15 16]


In [185]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


#Zmiana rozmiaru tablicy

In [187]:
np.ravel(A)

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [190]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [191]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [192]:
A.T #transponowanie tablicy - zamienia wiersze na kolumny, a kolumny na wiersze

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

#Maski logiczne

In [194]:
A = np.arange(start=-10,stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [195]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [196]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [197]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [198]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [199]:
np.bitwise_or(A < -4, A > 4)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])