<a href="https://colab.research.google.com/github/trirex79/python/blob/main/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Strona biblioteki: https://numpy.org/
Dokumentacja: https://numpy.org/doc/

Podstawowa biblioteka do obliczeń numerycznych w języku Python.

Aby zainstalować bibliotekę NumPy, użyj polecenia: pip install numpy

#Podstawy

In [1]:
pip install numpy;

In [4]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

#ARRAY
Wszystkie obiekty muszą być tego samego typu

##Array 1D

In [21]:
arr1 = np.array([1.5,3.2,4.1])
arr1
print(arr1)


[1.5 3.2 4.1]


In [22]:
type(arr1)

numpy.ndarray

In [23]:
arr1.ndim

1

In [24]:
arr1.shape

(3,)

In [25]:
arr1.size

3

In [26]:
arr1.dtype

dtype('float64')

##Array 2D

In [29]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [35]:
y = np.array([['aaa','bbb','ccc'],['ddd','eee','bbb']])
y

array([['aaa', 'bbb', 'ccc'],
       ['ddd', 'eee', 'bbb']], dtype='<U3')

In [30]:
x.ndim

2

In [36]:
y.ndim

2

In [31]:
x.shape

(2, 2)

In [37]:
y.shape

(2, 3)

In [32]:
x.size

4

In [33]:
x.dtype

dtype('int64')

In [38]:
y.dtype

dtype('<U3')

##Array 3D

In [48]:
z = np.array([
              [[1,4,5],[5,7,9]],
              [[1,2,3],[4,5,6]],
              [[1,4,5],[5,7,9]],
              [[1,2,3],[4,5,6]]
            ])
z

array([[[1, 4, 5],
        [5, 7, 9]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 4, 5],
        [5, 7, 9]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [49]:
z.ndim #3 wymiary

3

In [42]:
z.size

12

In [50]:
z.shape
# 4 tablice, 2 wiersze, 3 kolumny

(4, 2, 3)

#Typy danych

In [51]:
A =np.array([1,7,2])
A.dtype

dtype('int64')

In [52]:
A = np.array([1.5 ,2.6])
A.dtype

dtype('float64')

In [53]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [56]:
A = np.array([1,2,3], dtype='complex') #typy złożone
A.dtype

dtype('complex128')

In [55]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [57]:
B = np.array([1.1 ,2.2 ,3.0 ], dtype='int') #niejawna konwersja
B.dtype

dtype('int64')

In [58]:
B

array([1, 2, 3])

In [61]:
C =np.array([True,False])  # z dużej litery
C.dtype

dtype('bool')

In [63]:
pixel = np.array([120,230,255], dtype=np.uint8) # unsign int od 0 do 225 wystarczy do RGB
pixel.dtype

dtype('uint8')

#Tworzenie tabli

In [69]:
q = np.zeros(shape=(4,10))
q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
q.dtype #domyślny typ float

dtype('float64')

In [70]:
r = np.ones(shape=(5,8), dtype = np.uint8)
r

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [71]:
p = np.full(shape=(4,4),fill_value=5, dtype='int')
p

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [73]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [80]:
np.arange(start =100, stop=-20, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0, -10])

In [82]:
np.arange(start =0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [77]:
range(10)

range(0, 10)

In [78]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
np.linspace(start=0, stop=9 , num= 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
A.reshape((5,-1)) # 5 wierszy i odpowiednia liczba kolum  -1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [95]:
A.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])