<a href="https://colab.research.google.com/github/trirex79/python/blob/main/Podstawy/Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.19.5'

# <a name='a1'></a> Norma wektora, długość wektora w $R^{2}$ - długośc wektora w przestrzeni R2

${\mathbf  {v}} = [v_{1}, v_{2}]$   
$\left\|{\mathbf  {v}}\right\|={\sqrt  {v_{1}^{2}+v_{2}^{2}}}$

In [8]:
v1 = np.array([2,6])
v1

array([2, 6])

In [9]:
np.linalg.norm(v1)

6.324555320336759

### <a name='a2'></a> Norma euklidesowa w $R^{n}$ - długość wektora w przestrzeni Rn

$\left\|{\mathbf  {v}}\right\|={\sqrt  {v_{1}^{2}+v_{2}^{2}+\cdots +v_{n}^{2}}}$

In [6]:
v2 = np.array([-9, 12, 18])
v2

array([-9, 12, 18])

In [7]:
np.linalg.norm(v2)

23.430749027719962

#Odległość dwóch punktów na płaszczyźnie

In [10]:
p1 = np.array([4,0])
p2 = np.array([0,3])
np.linalg.norm(p1-p2)

5.0

In [11]:
p1 = np.array([0,4])
p2 = np.array([0,-3])
np.linalg.norm(p1-p2)

7.0

In [12]:
p3 = p1 - p2 
p3

array([0, 7])

##<a name='a4'></a> Odległóść dwóch punktów w przestrzeni $R^{n}$


 \begin{aligned}d(\mathbf {p} ,\mathbf {q} )=d(\mathbf {q} ,\mathbf {p} )&={\sqrt {(q_{1}-p_{1})^{2}+(q_{2}-p_{2})^{2}+\cdots +(q_{n}-p_{n})^{2}}}\\[8pt]&={\sqrt {\sum _{i=1}^{n}(q_{i}-p_{i})^{2}}}\end{aligned}

In [13]:
p1 = np.array([4,0,2])
p2 = np.array([2,0,3])
np.linalg.norm(p1-p2)

2.23606797749979

In [14]:
p1 = np.array([-1,4,0,2]) #jeżeli 4 wymiar jest taki sam w obu punktach to odległość się nie zmieni
p2 = np.array([-1,2,0,3])
np.linalg.norm(p1-p2)

2.23606797749979

In [15]:
p1 = np.array([-1,4,0,2])
p2 = np.array([1,2,0,3])
np.linalg.norm(p1-p2)

3.0

#Mnożenie macierzy